(async function(){'use strict';
const NAMES=['site-config','homepage','campaigns','brands','navigation','translations','pages'];const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];const clone=o=>JSON.parse(JSON.stringify(o));let data={};
async function load(){for(const n of NAMES){try{const r=await fetch(`config/${n}.json`,{cache:'no-store'});data[n]=await r.json()}catch{data[n]=clone(window.GR21_DEFAULTS?.[n]||{})}}try{const p=JSON.parse(localStorage.getItem('gr21_control_draft')||'null');if(p)NAMES.forEach(n=>{if(p[n])data[n]=p[n]})}catch{}paintAll()}
function status(s){const e=$('[data-status]');e.textContent=s;e.classList.add('show');clearTimeout(status.t);status.t=setTimeout(()=>e.classList.remove('show'),2400)}function val(id,v){const e=$(`[data-field="${id}"]`);if(e)e.value=v??''}function read(id){return $(`[data-field="${id}"]`)?.value??''}function pathSet(obj,path,value){const p=path.split('.');let o=obj;while(p.length>1){const k=p.shift();o[k]=o[k]||{};o=o[k]}o[p[0]]=value}
function paintSite(){const s=data['site-config'];['siteName','legalNameAr','legalNameEn','taglineAr','taglineEn','country','currency','baseUrl'].forEach(k=>val('site.'+k,s[k]));['phone','whatsapp','email','addressAr','addressEn','hoursAr','hoursEn'].forEach(k=>val('site.contact.'+k,s.contact?.[k]));['primary','primary2','leaf','gold','cream','radius'].forEach(k=>val('site.theme.'+k,s.theme?.[k]));const idx=$('[data-field="site.seoIndexable"]');if(idx)idx.checked=!!s.seoIndexable}
function paintHome(){const h=data.homepage,hero=h.hero||{};['kicker','titleAr','titleEn','copyAr','copyEn','image'].forEach(k=>val('home.hero.'+k,hero[k]));['labelAr','labelEn','href'].forEach(k=>{val('home.hero.primary.'+k,hero.primary?.[k]);val('home.hero.secondary.'+k,hero.secondary?.[k])});renderSections()}
function renderSections(){const box=$('[data-sections]');box.innerHTML=(data.homepage.sections||[]).map((x,i)=>`<div class="cc-section-row" draggable="true" data-section-index="${i}"><span class="cc-grip">⋮⋮</span><div><b>${escapeHTML(x.labelAr||x.id)}</b><small style="display:block;color:#78837a">${escapeHTML(x.labelEn||x.id)} · ${escapeHTML(x.id)}</small></div><button class="cc-toggle ${x.enabled!==false?'on':''}" data-toggle-section="${i}" aria-label="toggle"></button><span>${i+1}</span></div>`).join('');let drag=null;$$('[data-section-index]',box).forEach(row=>{row.addEventListener('dragstart',()=>{drag=+row.dataset.sectionIndex;row.classList.add('dragging')});row.addEventListener('dragend',()=>{row.classList.remove('dragging');drag=null});row.addEventListener('dragover',e=>e.preventDefault());row.addEventListener('drop',e=>{e.preventDefault();const to=+row.dataset.sectionIndex;if(drag===null||drag===to)return;const a=data.homepage.sections.splice(drag,1)[0];data.homepage.sections.splice(to,0,a);renderSections();draft()})});$$('[data-toggle-section]',box).forEach(b=>b.onclick=()=>{const i=+b.dataset.toggleSection;data.homepage.sections[i].enabled=data.homepage.sections[i].enabled===false?true:false;renderSections();draft()})}
function renderCampaigns(){const box=$('[data-campaigns]'),c=data.campaigns||{};box.innerHTML=Object.entries(c.campaigns||{}).map(([id,x])=>`<div class="cc-list-item" data-campaign="${escapeHTML(id)}"><div class="cc-form"><label>Campaign ID<input disabled value="${escapeHTML(id)}"></label><label>Kicker<input data-cprop="kicker" value="${escapeHTML(x.kicker||'')}"></label><label>Target<input data-cprop="target" value="${escapeHTML(x.target||'campaign.html')}"></label><label>العنوان<input data-cprop="ar" value="${escapeHTML(x.ar||'')}"></label><label>English title<input data-cprop="en" value="${escapeHTML(x.en||'')}"></label><label>Enabled<select data-cprop="enabled"><option value="true" ${x.enabled!==false?'selected':''}>On</option><option value="false" ${x.enabled===false?'selected':''}>Off</option></select></label><label class="full">الوصف<textarea data-cprop="copy_ar">${escapeHTML(x.copy_ar||'')}</textarea></label><label class="full">English copy<textarea data-cprop="copy_en">${escapeHTML(x.copy_en||'')}</textarea></label></div></div>`).join('');box.oninput=e=>{const item=e.target.closest('[data-campaign]');if(!item||!e.target.dataset.cprop)return;let v=e.target.value;if(e.target.dataset.cprop==='enabled')v=v==='true';data.campaigns.campaigns[item.dataset.campaign][e.target.dataset.cprop]=v;draft()};val('campaign.active',c.activeCampaign||'')}
function renderNav(){const box=$('[data-nav-main]');box.innerHTML=(data.navigation.main||[]).map((x,i)=>`<div class="cc-list-item" data-nav-index="${i}"><div class="cc-form"><label>Arabic<input data-nprop="ar" value="${escapeHTML(x.ar||'')}"></label><label>English<input data-nprop="en" value="${escapeHTML(x.en||'')}"></label><label>Href<input data-nprop="href" value="${escapeHTML(x.href||'')}"></label><label>Enabled<select data-nprop="enabled"><option value="true" ${x.enabled!==false?'selected':''}>On</option><option value="false" ${x.enabled===false?'selected':''}>Off</option></select></label></div></div>`).join('');box.oninput=e=>{const item=e.target.closest('[data-nav-index]');if(!item||!e.target.dataset.nprop)return;let v=e.target.value;if(e.target.dataset.nprop==='enabled')v=v==='true';data.navigation.main[+item.dataset.navIndex][e.target.dataset.nprop]=v;draft()}}
function renderBrands(){const box=$('[data-brands]');box.innerHTML=Object.entries(data.brands||{}).map(([name,b])=>`<div class="cc-list-item" data-brand="${escapeHTML(name)}"><div class="cc-form"><label>Name<input disabled value="${escapeHTML(name)}"></label><label>Logo<input data-bprop="logo" value="${escapeHTML(b.logo||'')}"></label><label>العنوان<input data-bprop="titleAr" value="${escapeHTML(b.titleAr||'')}"></label><label>English title<input data-bprop="titleEn" value="${escapeHTML(b.titleEn||'')}"></label><label class="full">الوصف<textarea data-bprop="copyAr">${escapeHTML(b.copyAr||'')}</textarea></label><label class="full">English copy<textarea data-bprop="copyEn">${escapeHTML(b.copyEn||'')}</textarea></label></div></div>`).join('');box.oninput=e=>{const item=e.target.closest('[data-brand]');if(!item||!e.target.dataset.bprop)return;data.brands[item.dataset.brand][e.target.dataset.bprop]=e.target.value;draft()}}
function renderAdvanced(){const name=$('[data-json-select]').value||'site-config';$('[data-json]').value=JSON.stringify(data[name],null,2)}function paintAll(){paintSite();paintHome();renderCampaigns();renderNav();renderBrands();renderAdvanced();const cat=window.GR_CATALOG_FALLBACK||{};const k=$$('[data-kpi]');if(k[0])k[0].textContent=(cat.products||[]).length;if(k[1])k[1].textContent=Object.keys(cat.categories||{}).length;if(k[2])k[2].textContent=Object.keys(data.campaigns?.campaigns||{}).length;if(k[3])k[3].textContent=(data.homepage?.sections||[]).filter(x=>x.enabled!==false).length;refreshPreview()}
function escapeHTML(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}function draft(){localStorage.setItem('gr21_control_draft',JSON.stringify(data));refreshPreview(false)}
function syncForms(){const s=data['site-config'];$$('[data-field^="site."]').forEach(e=>{const p=e.dataset.field.slice(5);pathSet(s,p,e.type==='checkbox'?e.checked:e.value)});const h=data.homepage;$$('[data-field^="home."]').forEach(e=>pathSet(h,e.dataset.field.slice(5),e.value));data.campaigns.activeCampaign=read('campaign.active');draft()}
function savePreview(){syncForms();localStorage.setItem('gr21_preview_bundle',JSON.stringify(data));status('Preview saved on this browser');refreshPreview(true)}function clearPreview(){localStorage.removeItem('gr21_preview_bundle');localStorage.removeItem('gr21_control_draft');status('Local preview cleared');location.reload()}
function download(name,obj){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)+'\n'],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function exportBundle(){syncForms();download('GOLDEN_ROOTS_V21_CONTENT_BUNDLE.json',{version:21,exportedAt:new Date().toISOString(),...data});status('Bundle exported')}
async function importBundle(file){const obj=JSON.parse(await file.text());NAMES.forEach(n=>{if(obj[n])data[n]=obj[n]});draft();paintAll();status('Bundle imported')}
async function writeFolder(){if(!window.showDirectoryPicker){status('Direct folder write is not supported in this browser');return}syncForms();const root=await showDirectoryPicker({mode:'readwrite'});const dir=await root.getDirectoryHandle('config',{create:true});for(const n of NAMES){const h=await dir.getFileHandle(n+'.json',{create:true}),w=await h.createWritable();await w.write(JSON.stringify(data[n],null,2)+'\n');await w.close()}status('Config files written to selected folder')}
let previewMode='mobile';function refreshPreview(force=true){if(!force)return;const f=$('[data-preview-frame]');if(f)f.src='index.html?adminPreview=1&cc='+Date.now()}function setDevice(mode){previewMode=mode;const d=$('.cc-preview-device');d.style.maxWidth=mode==='mobile'?'390px':mode==='tablet'?'820px':'100%';d.style.margin=mode==='desktop'?'0':'0 auto';$$('[data-device]').forEach(b=>b.classList.toggle('is-active',b.dataset.device===mode));refreshPreview()}
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('is-active',x===b));$$('.cc-tab').forEach(x=>x.classList.toggle('is-active',x.dataset.panel===b.dataset.tab))});$('[data-save-preview]').onclick=savePreview;$('[data-export]').onclick=exportBundle;$('[data-clear]').onclick=clearPreview;$('[data-write-folder]').onclick=()=>writeFolder().catch(e=>status('Write cancelled'));$('[data-import]').onchange=e=>e.target.files[0]&&importBundle(e.target.files[0]).catch(()=>status('Invalid bundle'));$('[data-json-select]').onchange=renderAdvanced;$('[data-json-apply]').onclick=()=>{const n=$('[data-json-select]').value;try{data[n]=JSON.parse($('[data-json]').value);draft();paintAll();status(n+' applied')}catch{status('Invalid JSON')}};$('[data-json-download]').onclick=()=>{const n=$('[data-json-select]').value;download(n+'.json',data[n])};$$('[data-device]').forEach(b=>b.onclick=()=>setDevice(b.dataset.device));document.addEventListener('input',e=>{if(e.target.matches('[data-field]'))syncForms()});
await load();setDevice('mobile');})();
