const CACHE='golden-roots-v23-d4606f1337';
const CORE=['./','./index.html','./collection.html','./product.html','./offline.html','./maintenance.html','./catalog.json','./assets/gr-v23.a153fa85b1ce.css','./assets/gr-v23.bb1f17aa92e3.js','./config/site-config.json','./config/homepage.json','./config/campaigns.json','./config/brands.json','./config/navigation.json','./config/translations.json','./config/pages.json','./assets/golden-roots-logo.webp','./assets/golden-roots-mark.webp','./assets/golden-roots-hero.webp'];
self.addEventListener('install',e=>e.waitUntil((async()=>{const c=await caches.open(CACHE);await Promise.allSettled(CORE.map(x=>c.add(x)));await self.skipWaiting()})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('golden-roots-')&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim()})()));
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting()});
async function timeoutFetch(req,ms=5500){const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),ms);try{return await fetch(req,{signal:ctl.signal})}finally{clearTimeout(tm)}}
async function networkFirst(req,fallback){try{const r=await timeoutFetch(req);if(r?.ok){const c=await caches.open(CACHE);c.put(req,r.clone())}return r}catch{return (await caches.match(req))||fallback}}
async function stale(req){const hit=await caches.match(req);const fresh=fetch(req).then(async r=>{if(r?.ok){const c=await caches.open(CACHE);c.put(req,r.clone())}return r}).catch(()=>null);return hit||fresh||(await caches.match('./offline.html'))}
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==location.origin)return;if(e.request.mode==='navigate'){e.respondWith(networkFirst(e.request,caches.match('./offline.html')));return}if(u.pathname.endsWith('.json')){e.respondWith(networkFirst(e.request,caches.match(e.request)));return}if(['script','style','image'].includes(e.request.destination)){e.respondWith(stale(e.request));return}e.respondWith(caches.match(e.request).then(x=>x||fetch(e.request)))});
